name: MoCo
favicon: null
layout_spectrum: 0.2192
typography_spectrum: 0.18375
title: Motion Coaching
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4e4e56'
    - '#1e93d1'
    - '#949599'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.5430708630010486
  saturation: 0.4801300519611686
  rhythmicContrast: 0.6733040139079094
purpose: []
