color:
  brandStrength: 0.3125
  saturation: 0.4801300519611686
  brandColors:
    - '#ffffff'
    - '#4e4e56'
    - '#1e93d1'
    - '#949599'
    - '#000000'
  lightness: 0.5430708630010486
  rhythmicContrast: 0.6733040139079094
title: Motion Coaching
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.2192
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: MoCo
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.18375
